/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iuAAbPUyl8T
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function ChainList2() {
  return (
    <div key="1" className="max-w-4xl mx-auto p-6">
      <div className="flex justify-between items-center mb-6">
        <div className="flex space-x-4 items-center">
          <div className="relative">
            <MicroscopeIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
            <Input className="pl-10" placeholder="Search Networks" />
          </div>
          <label className="flex items-center space-x-2">
            <input className="form-checkbox" type="checkbox" />
            <span>Include Testnets</span>
          </label>
        </div>
        <Button className="bg-red-500 hover:bg-red-600 text-white">Connect Wallet</Button>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <Card className="w-full">
          <CardHeader>
            <div className="flex items-center space-x-3">
              <BitcoinIcon className="w-6 h-6" />
              <CardTitle>Ethereum Mainnet</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between items-center">
              <div>
                <div className="text-sm text-gray-600">ChainID</div>
                <div className="font-medium">1 (0x1)</div>
              </div>
              <div>
                <div className="text-sm text-gray-600">Currency</div>
                <div className="font-medium">ETH</div>
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex justify-between">
            <Button variant="outline">Connect Wallet</Button>
            <ChevronDownIcon className="text-gray-400" />
          </CardFooter>
        </Card>
        <Card className="w-full">
          <CardHeader>
            <div className="flex items-center space-x-3">
              <BanknoteIcon className="w-6 h-6" />
              <CardTitle>BNB Smart Chain Mainnet</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex justify-between items-center">
              <div>
                <div className="text-sm text-gray-600">ChainID</div>
                <div className="font-medium">56 (0x38)</div>
              </div>
              <div>
                <div className="text-sm text-gray-600">Currency</div>
                <div className="font-medium">BNB</div>
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex justify-between">
            <Button variant="outline">Connect Wallet</Button>
            <ChevronDownIcon className="text-gray-400" />
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}


function MicroscopeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>
  )
}


function BitcoinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11.767 19.089c4.924.868 6.14-6.025 1.216-6.894m-1.216 6.894L5.86 18.047m5.908 1.042-.347 1.97m1.563-8.864c4.924.869 6.14-6.025 1.215-6.893m-1.215 6.893-3.94-.694m5.155-6.2L8.29 4.26m5.908 1.042.348-1.97M7.48 20.364l3.126-17.727" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function BanknoteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="12" x="2" y="6" rx="2" />
      <circle cx="12" cy="12" r="2" />
      <path d="M6 12h.01M18 12h.01" />
    </svg>
  )
}
