/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bjCYzscZ3Zp
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function ShoppingList() {
  return (
    <section className="w-full py-12">
      <div className="container grid gap-6 md:gap-8 px-4 md:px-6 max-w-xl mx-auto lg:max-w-none">
        <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <div className="grid gap-1">
            <h1 className="text-2xl font-bold tracking-tight">Shop by Category</h1>
            <p className="text-gray-500 dark:text-gray-400">Explore our diverse product categories.</p>
          </div>
        </div>
        <div className="grid lg:grid-cols-3 gap-8">
          <Card>
            <CardHeader>
              <img
                alt="Electronics"
                className="rounded-lg object-cover w-full aspect-[3/4] group-hover:opacity-50 transition-opacity"
                height="600"
                src="/placeholder.svg"
                width="450"
              />
              <h3 className="font-semibold">Electronics</h3>
              <p className="text-sm leading-none">Discover the latest electronic devices.</p>
            </CardHeader>
            <CardContent>
              <Button variant="outline">Shop Now</Button>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <img
                alt="Fashion"
                className="rounded-lg object-cover w-full aspect-[3/4] group-hover:opacity-50 transition-opacity"
                height="600"
                src="/placeholder.svg"
                width="450"
              />
              <h3 className="font-semibold">Fashion</h3>
              <p className="text-sm leading-none">Find the newest trends in fashion.</p>
            </CardHeader>
            <CardContent>
              <Button variant="outline">Shop Now</Button>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <img
                alt="Home & Kitchen"
                className="rounded-lg object-cover w-full aspect-[3/4] group-hover:opacity-50 transition-opacity"
                height="600"
                src="/placeholder.svg"
                width="450"
              />
              <h3 className="font-semibold">Home & Kitchen</h3>
              <p className="text-sm leading-none">Furnish your space with stylish and practical items.</p>
            </CardHeader>
            <CardContent>
              <Button variant="outline">Shop Now</Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
