/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/noyCrEUEmEH
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import { CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

export function TestComponent() {
  return (
    <div className="flex flex-col h-screen bg-gray-100">
      <header className="p-4 bg-white border-b border-gray-200 flex justify-between items-center">
        <h1 className="text-2xl font-bold">Telegram</h1>
        <div className="flex items-center gap-3">
          <Avatar className="h-9 w-9">
            <AvatarImage alt="User" src="/placeholder-avatar.jpg" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <div className="grid gap-0.5 text-xs">
            <div className="font-medium">Username</div>
            <div className="text-gray-500 dark:text-gray-400">username@telegram.com</div>
          </div>
        </div>
      </header>
      <main className="flex flex-1 overflow-hidden">
        <aside className="w-80 border-r border-gray-200 p-4 overflow-auto">
          <Button className="w-full py-2 mb-4">
            New Conversation
            <PlaneIcon className="ml-2 w-4 h-4" />
          </Button>
          <Card className="w-full">
            <CardContent className="p-4">
              <Tabs className="flex flex-col gap-2 items-start" defaultValue="chats">
                <TabsList className="w-full justify-start">
                  <TabsTrigger value="chats">Chats</TabsTrigger>
                  <TabsTrigger value="groups">Groups</TabsTrigger>
                  <TabsTrigger value="channels">Channels</TabsTrigger>
                </TabsList>
                <TabsContent className="p-1" value="chats">
                  <div className="mb-4 p-2 rounded-lg hover:bg-gray-200 cursor-pointer">
                    <div className="flex items-center gap-3">
                      <Avatar className="h-6 w-6">
                        <AvatarImage alt="Chat User" src="/placeholder-avatar.jpg" />
                        <AvatarFallback>CU</AvatarFallback>
                      </Avatar>
                      <div className="grid gap-0.5 text-sm">
                        <div className="font-medium">Chat User</div>
                        <div className="text-gray-500 dark:text-gray-400">Last message...</div>
                      </div>
                    </div>
                  </div>
                </TabsContent>
              </Tabs>
            </CardContent>
          </Card>
        </aside>
        <section className="flex-1 p-4">
          <Card className="w-full h-full flex flex-col">
            <CardContent className="p-4 flex-1 overflow-auto">
              <div className="mb-4 p-2 rounded-lg bg-green-100 w-max">
                <div className="text-sm">Message...</div>
              </div>
            </CardContent>
            <div className="p-4 border-t border-gray-200">
              <div className="flex items-center gap-2">
                <Input className="flex-1" placeholder="Type a message..." />
                <Button>
                  Send
                  <PlaneIcon className="ml-2 w-4 h-4" />
                </Button>
              </div>
            </div>
          </Card>
        </section>
      </main>
    </div>
  )
}


function PlaneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  )
}
